### PR TITLE
Error handling and exit built in

### PR DESCRIPTION
**Pull request by SantiagoHerreG**
please check new features

@Daransoto

### CODE REVIEW

**Review by Daransoto — CHANGES_REQUESTED** [review]
El -1 en el getline indicaría EOF, entonces no hay que poner otro.

**Comment by SantiagoHerreG** [comment]
-1 in getline deleted

**Comment by SantiagoHerreG** [comment]
@Daransoto please check updates

**Review by Daransoto — APPROVED** [review]
All perfect

**Pull request merged**
